config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'pages/about'

  get 'pages/store'

  get 'pages/faq'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def store
  end

  def faq
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BluePotatoSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

 	<%= render "shared/nav" %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/faq.html.erb
<h1>Pages#faq</h1>
<p>Find me in app/views/pages/faq.html.erb</p>

app/views/pages/home.html.erb
<h1>The Blue Potato</h1>

app/views/pages/store.html.erb
<h1>Pages#store</h1>
<p>Find me in app/views/pages/store.html.erb</p>

app/views/shared/_nav.html.erb
<div class="nav-bar">
	<%= link_to "Home", root_path %>
	<%= link_to "About", pages_about_path %>
	<%= link_to "Store", pages_store_path %>
	<%= link_to "FAQ", pages_faq_path %>
</div>